### ISSUE TITLE
StartSocket(55666);

### ISSUE THREAD

**Issue by kabiri** [WillHubner/Horse-SocketIO#7]
It gives this error when I run the example :
Project Server.exe raised exception class EIdSocketError with message 'Socket Error # 10048
Address already in use.'.

Why did you use this line on the server?
```
initialization
  StartSocket(55666);
```
What happens if we have several different server programs on one computer?
Of course, in my case, another program already uses this port.
So is not it better to be able to set this from within the program

**Comment by WillHubner** [comment]
yes, if you open many instances, and all using 55666 port, cause this error.

Change the port and i believe that runs ok.

**Comment by kabiri** [comment]
The port hard coded
I know I can change it
It is better to define the port as a property.
So that each program defines the desired value for the port at runtime.

**Comment by WillHubner** [comment]
Hi!!

I added the port on middleware!!

Thanks!!


***@***.***
Willian Hübner
Coordenador de Análise e Desenvolvimento de Sistemas
Unifasipe – Sinop/MT


De: ***@***.***>
Enviado:quinta-feira, 7 de abril de 2022 02:49
Para: ***@***.***>
Cc:Willian ***@***.***>; State ***@***.***>
Assunto: Re: [WillHubner/Horse-SocketIO] StartSocket(55666); (Issue #7)


The port hard coded
I know I can change it
It is better to define the port as a property.
So that each program defines the desired value for the port at runtime.

**Comment by kabiri** [comment]
Thanks
